[[redirects]]
  from = "/"
  to = "http://localhost:3001/api/*"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"